// ========================================
// ADMIN DUMMY DATA
// ========================================

export const usersData = [
  {
    id: 1,
    name: "Ayesha Khan",
    email: "ayesha.khan@email.com",
    role: "User",
    status: "Active",
    joinDate: "2024-08-15",
    phone: "+92-300-1234567",
  },
  {
    id: 2,
    name: "Ahmed Ali",
    email: "ahmed.ali@email.com",
    role: "User",
    status: "Active",
    joinDate: "2024-09-20",
    phone: "+92-321-7654321",
  },
  {
    id: 3,
    name: "Bilal Ahmad",
    email: "bilal.ahmad@email.com",
    role: "User",
    status: "Inactive",
    joinDate: "2024-07-10",
    phone: "+92-333-9876543",
  },
  {
    id: 4,
    name: "Fatima Zahra",
    email: "fatima.zahra@email.com",
    role: "User",
    status: "Active",
    joinDate: "2024-10-05",
    phone: "+92-312-5555555",
  },
  {
    id: 5,
    name: "Hassan Raza",
    email: "hassan.raza@email.com",
    role: "User",
    status: "Active",
    joinDate: "2024-11-12",
    phone: "+92-345-8888888",
  },
];

export const lawyersData = [
  {
    id: 1,
    name: "Adv. Ahmed Raza",
    email: "ahmed@law.com",
    specialization: "Criminal Law",
    experience: "5 Years",
    status: "Active",
    verified: true,
    phone: "+92-300-2222222",
    city: "Lahore",
    barCouncil: "SCBA",
  },
  {
    id: 2,
    name: "Adv. Sara Malik",
    email: "sara@law.com",
    specialization: "Family Law",
    experience: "3 Years",
    status: "Active",
    verified: true,
    phone: "+92-321-3333333",
    city: "Karachi",
    barCouncil: "SBCA",
  },
  {
    id: 3,
    name: "Adv. Ali Hassan",
    email: "ali.hassan@law.com",
    specialization: "Corporate Law",
    experience: "8 Years",
    status: "Active",
    verified: true,
    phone: "+92-333-4444444",
    city: "Islamabad",
    barCouncil: "IBCA",
  },
  {
    id: 4,
    name: "Adv. Zainab Khan",
    email: "zainab.khan@law.com",
    specialization: "Property Law",
    experience: "4 Years",
    status: "Inactive",
    verified: false,
    phone: "+92-312-5555555",
    city: "Multan",
    barCouncil: "SCBA",
  },
  {
    id: 5,
    name: "Adv. Muhammad Farooq",
    email: "farooq@law.com",
    specialization: "Commercial Law",
    experience: "6 Years",
    status: "Active",
    verified: true,
    phone: "+92-345-6666666",
    city: "Peshawar",
    barCouncil: "PKCA",
  },
];

export const lawFirmsData = [
  {
    id: 1,
    name: "Justice Legal Associates",
    email: "justice@lawfirm.com",
    city: "Lahore",
    lawyersCount: 12,
    status: "Active",
    verified: true,
    phone: "+92-42-35880555",
    established: "2015",
    website: "www.justicelegals.com",
  },
  {
    id: 2,
    name: "Al-Haq Law Firm",
    email: "alhaq@lawfirm.com",
    city: "Karachi",
    lawyersCount: 8,
    status: "Active",
    verified: true,
    phone: "+92-21-34961234",
    established: "2018",
    website: "www.alhaqlaw.com",
  },
  {
    id: 3,
    name: "Rizvi & Associates",
    email: "rizvi@lawfirm.com",
    city: "Islamabad",
    lawyersCount: 15,
    status: "Active",
    verified: true,
    phone: "+92-51-28445566",
    established: "2010",
    website: "www.rizvit.com",
  },
  {
    id: 4,
    name: "Legal Solutions Pakistan",
    email: "solutions@lawfirm.com",
    city: "Multan",
    lawyersCount: 5,
    status: "Inactive",
    verified: false,
    phone: "+92-61-4567890",
    established: "2019",
    website: "www.legalsolutions.pk",
  },
  {
    id: 5,
    name: "Shaukat & Co. Law Firm",
    email: "shaukat@lawfirm.com",
    city: "Peshawar",
    lawyersCount: 10,
    status: "Active",
    verified: true,
    phone: "+92-91-5218888",
    established: "2016",
    website: "www.shaukatlaw.com",
  },
];

export const casesData = [
  {
    id: "CASE-001",
    title: "Divorce Settlement",
    user: "Ayesha Khan",
    lawyer: "Adv. Sara Malik",
    firm: "Al-Haq Law Firm",
    city: "Karachi",
    status: "In Progress",
    priority: "High",
    date: "2025-01-10",
    type: "Family Law",
  },
  {
    id: "CASE-002",
    title: "Property Dispute",
    user: "Ahmed Ali",
    lawyer: "Adv. Zainab Khan",
    firm: "Justice Legal Associates",
    city: "Lahore",
    status: "Open",
    priority: "Medium",
    date: "2025-01-12",
    type: "Property Law",
  },
  {
    id: "CASE-003",
    title: "Cyber Crime Complaint",
    user: "Bilal Ahmad",
    lawyer: "—",
    firm: "—",
    city: "Islamabad",
    status: "Pending",
    priority: "Critical",
    date: "2025-01-15",
    type: "Criminal Law",
  },
  {
    id: "CASE-004",
    title: "Contract Breach",
    user: "Fatima Zahra",
    lawyer: "Adv. Ali Hassan",
    firm: "Rizvi & Associates",
    city: "Islamabad",
    status: "Resolved",
    priority: "Medium",
    date: "2024-12-20",
    type: "Corporate Law",
  },
  {
    id: "CASE-005",
    title: "Inheritance Dispute",
    user: "Hassan Raza",
    lawyer: "Adv. Ahmed Raza",
    firm: "Justice Legal Associates",
    city: "Lahore",
    status: "In Progress",
    priority: "High",
    date: "2025-01-05",
    type: "Family Law",
  },
];
